version: '3.8'

services:
  ctrip_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctrip_frontend
    restart: always
    ports:
      - "3001:3001"
    networks:
      - ctrip-network
    depends_on:
      - ctrip_api

networks:
  ctrip-network:
    external: true